spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/sbms
    username: root
    hikari:
      maximum-pool-size: 20
      
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
   
  batch:
    jdbc:
      initialize-schema: always
    